require 'machete/matchers/app_running'
require 'machete/matchers/app_has_internet_traffic'
require 'machete/matchers/app_has_logged'
require 'machete/matchers/app_has_file'
require 'machete/matchers/app_has_page_body'
