#!/bin/bash -l

set -e

trap 'echo "error in buildpack-build ${BASH_SOURCE} ${LINENO}"' ERR

BUILDPACK_FILE_PATTERN="*_buildpack*.zip"

mode=$1
rspec_options=$2

if [ $# -eq 0 ] || ([ "$mode" != "online" ] && [ "$mode" != "offline" ]); then
  echo "Usage:"
  echo "  ./buildpack-build online|offline [rspec options]"
  exit 1
fi

if [[ -z "$rspec_options" ]]
then
  rspec_options=cf_spec
fi

if [ "$mode" == "online" ]; then
  api=api.10.244.0.34.xip.io
  export VAGRANT_CWD="$HOME/workspace/bosh-lite"
else
  api=api.10.245.0.34.xip.io
  export VAGRANT_CWD="$HOME/workspace/bosh-lite-2nd-instance"
fi

$VAGRANT_CWD/scripts/add-route

echo -e "\n******* Packaging $mode buildpack"

echo -e "\n******* Fetching CF CLI details"
which cf
cf --version

echo -e "\n******* Building $mode package"
rm -f ${BUILDPACK_FILE_PATTERN}
time ./bin/package $mode

echo -e "\n******* Detecting language"
language=$(ls ${BUILDPACK_FILE_PATTERN} | cut -d_ -f1)
echo -e "Language detected: ${language}"

echo -e "\n******* Creating buildpack on CF"

cf api $api --skip-ssl-validation
cf login -u admin -p admin -o pivotal -s integration
cf delete-buildpack ${language}-test-buildpack -f
cf create-buildpack ${language}-test-buildpack ${BUILDPACK_FILE_PATTERN} 1 --enable

echo -e "\n******* Configuring RVM"
export PATH=/Users/pivotal/.rvm/bin:$PATH
rvm use default

echo -e "\n******* Running specs"
BUNDLE_GEMFILE=cf.Gemfile bundle --no-cache
BUNDLE_GEMFILE=cf.Gemfile BUILDPACK_MODE=$mode rspec --format documentation --pattern "{integration,unit}/*_spec.rb" $rspec_options
