#!/bin/bash
set -eo pipefail

__indent() {
  local msg=$1
  echo "-----> $msg"
}

__ensure_space() {
  __indent "Setting up org and space"

  cf create-org pivotal
  cf create-space integration -o pivotal
  cf target -o pivotal -s integration
}

__target_api() {
  __indent "Targeting CF API"

  echo $(cf api)
  __ensure_space
}

__target_api
