#!/bin/bash -l
set -eo pipefail

__parse_arguments() {
  number_of_arguments=$#
  mode=${1:-''}
}

__check_usage() {
  if [ ${number_of_arguments} -ne 1 ] || ([ "$mode" != "lucid" ] && [ "$mode" != "trusty" ]); then
    echo "Usage:"
    echo "  $0 lucid|trusty"
    exit 1
  fi
}

__ensure_space() {
  echo "-----> Setting up org and space"
  
  cf create-org pivotal
  cf create-space integration -o pivotal
  cf target -o pivotal -s integration
}

__target_api() {
  echo "-----> Targetting CF API"
  
  if [ "$mode" = "lucid" ]; then
      cf api api.10.244.0.34.xip.io --skip-ssl-validation
  else
      cf api api.10.244.1.34.xip.io --skip-ssl-validation
  fi

  set +e
  cf login -u admin -p admin -o pivotal -s integration

  login_result=$?
  set -e

  if [ $login_result -ne 0 ]; then
    __ensure_space
  fi
}

__target_bosh() {
  echo "-----> Targetting bosh"

  set +e
  if [ "$mode" = "lucid" ]; then
    bosh target 192.168.50.4
    bosh login admin admin
    bosh deployment ../bosh-lite/manifests/cf-manifest.yml
  elif [ "$mode" = "trusty" ]; then
    bosh target 192.168.200.4
    bosh login admin admin
    bosh deployment ../bosh-lite-trusty/manifests/cf-manifest.yml
  fi
  set -e
}

__reset_postgres_security_groups() {
  __target_api

  echo "-----> Setting up security groups for PostgreSQL access"

  cf delete-security-group postgres-access -f
  cf create-security-group postgres-access "./scripts/assets/${mode}_postgres_security_group.json"
  cf bind-security-group postgres-access pivotal integration
}

__ensure_internet_traffic_logging() {
  __target_bosh

  echo "-----> Setting up internet egress logging"

  VAGRANT_CWD=$HOME/workspace/bosh-lite bundle exec ./scripts/enable_bosh_enterprise_firewall.rb
}

__create_database_users() {
  __target_bosh

  echo "-----> Creating database users"

  postgres_path_command="postgres_path=\`find /var/vcap/data/packages/postgres/*/ -name bin\`"
  change_path_command="PATH=\$postgres_path:\$PATH"
  create_machete_user_command="psql -h 0.0.0.0 -U vcap -p 5524 -d postgres -c \"create user machete with encrypted password 'machete' SUPERUSER\""
  create_buildpacks_user_command="psql -h 0.0.0.0 -U vcap -p 5524 -d postgres -c \"create user buildpacks with encrypted password 'buildpacks'\""
  bosh ssh --gateway_user vcap postgres_z1 0 --default_password p "$postgres_path_command;$change_path_command;$create_machete_user_command;$create_buildpacks_user_command"
}


__parse_arguments $@
__check_usage

__reset_postgres_security_groups
__ensure_internet_traffic_logging
__create_database_users
